apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  PORT: "8000"
  DB_HOST: "mysql-service"
  DB_NAME: "appdb"
  DB_USER: "appuser"